config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :blog_posts
  root to: "pages#splash"

  ['home','about','blog','resume','portfolio','contact'].each do |choice|
    get choice, controller: "pages", action: choice
  end

  post 'contact', controller: 'pages', action: 'info'
  get 'next_splash', controller: "pages", action: 'splash'

  get 'third_party_scenarios.xlsx', to: 'pages#third_party_scenarios'
end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
  belongs_to :user, inverse_of: :blog_posts
  validates :user, presence: true

  def most_recent(n)
    @current_user.blog_posts.order_by(pub_date: :desc).last(5).reverse.each
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:user_id, :guid, :title, :description, :link, :pub_date)
    end
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
  ONE_YEAR = (525600 * 60)
  ONE_MONTH = (60*60*24*30)
  ONE_WEEK = (60*60*24*7)
  ONE_DAY = (60*24)

  def time_ago(post)
    dt = (Time.now - post.pub_date)
    [['year', ONE_YEAR], ['month',ONE_MONTH],
     ['week', ONE_WEEK], ['day',ONE_DAY]].each do |name, period|
       if dt >= 2 * period
         return "#{(dt / period).floor} #{name.pluralize} ago"
       elsif dt > period
         return "#{(dt / period).floor} #{name} ago"
       end
    end
  end
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :guid %><br>
    <%= f.text_field :guid %>
  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :pub_date %><br>
    <%= f.datetime_select :pub_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Guid</th>
      <th>Title</th>
      <th>Description</th>
      <th>Link</th>
      <th>Pub date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blog_posts.each do |blog_post| %>
      <tr>
        <td><%= blog_post.user_id %></td>
        <td><%= blog_post.guid %></td>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.description %></td>
        <td><%= blog_post.link %></td>
        <td><%= blog_post.pub_date %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @blog_post.user_id %>
</p>

<p>
  <strong>Guid:</strong>
  <%= @blog_post.guid %>
</p>

<p>
  <strong>Title:</strong>
  <%= @blog_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @blog_post.description %>
</p>

<p>
  <strong>Link:</strong>
  <%= @blog_post.link %>
</p>

<p>
  <strong>Pub date:</strong>
  <%= @blog_post.pub_date %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@blog_post) %> |
<%= link_to 'Back', blog_posts_path %>