config/routes.rb
Rails.application.routes.draw do
  resources :skills
  resources :blog_posts
  root to: "pages#splash"

  ['home','about','blog','resume','portfolio','contact'].each do |choice|
    get choice, controller: "pages", action: choice
  end

  post 'contact', controller: 'pages', action: 'info'
  get 'next_splash', controller: "pages", action: 'splash'

  get 'third_party_scenarios.xlsx', to: 'pages#third_party_scenarios'
end

app/views/pages/_about.html.erb
<div id="about" class="hash-link">
</div>

<div class="wrapper wrapper-style2">
  <div class="container">
    <div class="row 200%">
      <div class="12u">
        <!-- Content -->
        <div id="content">
          <section class="post box">
            <header>
              <h2 class="section-headline">About Me</h2>
            </header>
            <a href="#" class="image left"><%= image_tag("me.jpg", :alt => @current_user.full_name) %></a>

            <p class="section-content">
              Like most people, I became a software engineer the old-fashioned way.
              I majored in math and economics, then took a job as news director at an NPR station.
              After that I switched into actuarial science.  Now here I am.
            </p>

            <p class="section-content">
              Makes perfect sense, right?
            </p>

            <p class="section-content">
              It&apos;s an unique path, and there&apos;s a connecting tissue in all these endeavors.
              As long as I remember, I&apos;ve loved to ask questions and solve puzzles.
              Math problems were puzzles in their purest forms.
              Acturial science was a way to get paid to solve those puzzles.
              Economics was solving puzzles related to real life public policy.
              Journalism was an opportunity to ask those exact questions to the people who had influence.
            </p>

            <p class="section-content">
              I use the skills from all three activities every day as a software engineer.
            </p>
          </section>

          <section class="post">
            <h4 class="section-headline">
              Is Economics Like Software?
            </h4>

            <p class="section-content">
              The mindset of an economict is not much different from a software security consultant.
              Both people must anticipate how an unscrupulous end-user will try to game the system.
              Trying to anticipate how someone will exploit a loophole in the tax-code is the same
              mindset needed to defend a website from a SQL injection or denial of service attack.
            </p>
          </section>

          <section class="post">
            <h4 class="section-headline">
              Journalism Teaches Good UX
            </h4>

            <p class="section-content">
              Journalism at the time was a way to ask interesting policy questions to those with influence.
              While I&apos;ve stored away my microphone for many years, but the journalism mindset will never leave me.
            </p>

            <p class="section-content">
              The mindset from journalism overlaps heavily with we in software call &quot;UX.&quot;
              Just like radio listeners, users who visit a website aren't lending their full attention.
              Crisp, vivid writing was essential.  A reporter only has one chance to capture a listener&apos; attention.
              Just like a user on an e-commerce site makes a snap judgment in a fraction of a minute.
              A one mentor gave me a pearl of wisdom that is relevant for clean web design:
              &quot;If you don&apos;t have to leave it in, you have to take it out.&apos;
            </p>
          </section>

          <section class="post">
            <h4 class="section-headline">
              <span class="group">From Actuary</span>
              <span class="group">To Developer</span>
            </h4>

            <p class="section-content">
              Any data-scientist will agree with this statement.
              A disproportionate amount of the work is simply the plumbing.
              It&apos;s organizing data.  Figuring out how to make your design scalable.
              It requires figuring out how to automate repeated manual tasks.
              It requires running a battery of tests every time a change is made to the model.
              It requires managing complexity.  In short, it&apos;s software engineering.
            </p>

            <p class="section-content">
              Over time more of my day was consumed writing actuarial software, and accounting for data flow.
              It started off with a few VBA macros in Excel.  By the end of my time, I had built an end-to-end
              audit trail using Python, and PostgreSQL.  It increased the accuracy of reported numbers, and
              reduced the time needed to produce them.
            </p>

            <p class="section-content">
              By the end of my tenure, and after passing some grueling actuarial exams, it became clear that
              building things was more interesting and satisfying than the actuarial and financial analysis portion.
              When I had that epiphany, I saved my money, made the switch, and moved to San Francisco.
            </p>

          </section>

        </div>
      </div>

    </div><!-- End .row.200% -->

  </div>
</div>

app/views/pages/_banner.html.erb
<section id="banner-intro">
  <h2 class="section-headline">
    <span class="group">
      <span class="group">Software Engineer,</span>
    </span>
    <span class="group">
      <span class="group">Mathematician,</span>
      <span class="group">Reporter</span>
    </span>
  </h2>

  <div>
    <p class="section-caption">
      <span class="group group-secondary">
        <span class="group">Everything in life has</span>
        <span class="group">been a puzzle to solve.</span>
      </span>
      <span class="group group-secondary">
        <span class="group">Math puzzles as an actuary,</span>
        <span class="group">policy puzzles as a reporter</span>
      </span>
    </p>
  </div>

  <h3 class="section-caption">
    <span class="group">Software is</span>
    <span class="group">just another puzzle.</span>
  </h3>

</section>

app/views/pages/_contact_methods.html.erb
<ul class="contact">
  <li style="display: none"></li>
  <li>
    <span class="icon fa-home"></span>
    <div class="data">
      <%= @current_user.address.gsub("\n", "<br>").html_safe %>
    </div>
  </li>
  <li>
    <span class="email icon fa-envelope"></span>
    <div class="container">
      <% if @recaptcha_success %>
        <%= @current_user.email %>
      <% else %>
        <form action="?" method="POST">
          <%= raw recaptcha_tags %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button type='submit'>Ask For Email Address</button>
        </form>
      <% end %>
    </div>
  </li>
  <li>
    <span class="icon fa-phone"></span>
    <%= @current_user.phone %>
  </li>
</ul> <!-- end .contact -->

app/views/pages/_contact_social_media.html.erb
<ul class="contact">
  <li style="display: none"></li>

  <li>
    <span class="email icon fa-github"></span>
    <%= link_to 'GitHub', @current_user.github, target: '_blank' %>
  </li>
  <li>
    <span class="email icon fa-linkedin"></span>
    <%= link_to 'LinkedIn', @current_user.linkedin, target: '_blank' %>
  </li>
  <li>
    <span class="email icon fa-stack-overflow"></span>
    <%= link_to 'Stack Overflow', @current_user.stack_overflow, target: '_blank' %>
  </li>
</ul> <!-- end .contact -->

app/views/pages/_footer.html.erb
<!-- Footer Wrapper -->
<div id="footer-wrapper">
    <div id="footer" class="container">
      <!-- Copyright -->
      <div id="copyright">
        <span>&copy; <%= @current_user.full_name %> <%= Time.now.year %>,&nbsp; All rights reserved.</span>
      </div>
    </div>
</div>

app/views/pages/_header.html.erb
<!-- Header Wrapper -->
  <div id="header-wrapper">
    <div class="container">

      <!-- Header -->
      <div id="header">
        <div class="inner">

          <!-- Logo -->
          <div class="navbar-left">
            <h1><%= link_to @current_user.full_name, root_url %></h1>
          </div>

          <% item_maker = Proc.new do |name, options={}| %>
            <% flag = (active.downcase == name.downcase) %>
            <% url = options[:url] || send("#{name.downcase}_path") %>
            <% options.delete(:url) if options.include?(:url) %>
            <li class="navbar-list-item <%= flag ? 'current_page_item': '' %>">
              <%= link_to name, url, options %>
            </li>
          <% end %>

          <% menu_maker = Proc.new do %>
            <% ['Home'].each &item_maker %>
            <% item_maker.call 'Blog', url: @current_user.blog, target: '_blank' %>
            <% ['Resume','Portfolio','Contact'].each &item_maker %>
          <% end %>

          <!-- Nav -->
          <div id="nav">
            <ul class="navbar-list">
              <% menu_maker.call %>
            </ul>
          </div>

        </div> <!-- End Inner -->
      </div> <!-- End #header, really it's a navbar -->

    </div>
    <div id="header-wrapper-ie8"></div>
  </div>

  <!-- Main Wrapper -->
  <div id="navbar-offset"></div>

app/views/pages/_navbar.html.erb
<!-- Header Wrapper -->
  <div id="header-wrapper">
    <div class="container">

      <!-- Header -->
        <div id="header">
          <div class="inner">

            <!-- Logo -->
              <h1><a href="index.html" id="logo">Steve Zelaznik</a></h1>

            <!-- Nav -->
              <nav id="nav">
                <ul>
                  <li class="<%= (active=='root') ? 'current_page_item' : '' %>"><a href="index.html">Homepage</a></li>
                  <li class="<%= (active=='dropdown') ? 'current_page_item' : '' %>">
                    <a href="#">Dropdown</a>
                    <ul>
                      <li><a href="#">Lorem ipsum dolor</a></li>
                      <li><a href="#">Magna phasellus</a></li>
                      <li>
                        <a href="#">Phasellus consequat</a>
                        <ul>
                          <li><a href="#">Lorem ipsum dolor</a></li>
                          <li><a href="#">Phasellus consequat</a></li>
                          <li><a href="#">Magna phasellus</a></li>
                          <li><a href="#">Etiam dolore nisl</a></li>
                        </ul>
                      </li>
                      <li><a href="#">Veroeros feugiat</a></li>
                    </ul>
                  </li>
                  <li class="<%= (active=='left_sidebar') ? 'current_page_item' : '' %>"><a href="left-sidebar.html">Left Sidebar</a></li>
                  <li class="<%= (active=='right_sidebar') ? 'current_page_item' : '' %>"><a href="right-sidebar.html">Right Sidebar</a></li>
                  <li class="<%= (active=='no_sidebar') ? 'current_page_item' : '' %>"><a href="no-sidebar.html">No Sidebar</a></li>
                </ul>
              </nav>

          </div>
        </div>

    </div>
    <div id="header-wrapper-ie8"></div>
  </div>

app/views/pages/_skills.html.erb
<div id="skills" class="hash-link">
</div>

<!-- Intro Wrapper -->
<div class="wrapper wrapper-style2">
  <div class="container">
    <div class="row">
      <div class="12u">

        <!-- Intro -->
        <section id="skills-intro">
          <header class="section-header">
            <h2 class="section-headline">
              <span class="group">Computer<span> / <span class="group">Technical Skills</span>
            </h2>
            <p class="section-caption">
              <span class="group">
                <span class="group">An affinity for</span>
                <span class="group">scripting languages,</span>
              </span>
              <span class="group">
                <span class="group">SQL databases,</span>&nbsp;<span>and</span>
                <span class="group">unit-testing frameworks.</span>
              </span>
              </p>
          </header>

          <div class="skills-table">
            <% @current_user.skills.each do |skill| %>
              <div class="skills-item">
                <%= image_tag skill.image_url, class: 'skills-item-image', alt: skill.name %>
                <h3 class="section-item-label skills-item-label"><%= skill.name %></h3>
              </div>
            <% end %>
          </div> <!-- end .row -->
        </section> <!-- end #intro -->

      </div> <!-- End .12u -->
    </div>
  </div>
</div> <!-- end intro wrapper -->

app/views/pages/contact.html.erb
<script type='text/javascript'>
  function onClickOutside($root_path, callback) {
    $(document).on('click', function(e) {
      if ( $(e.target).closest($root_path).length > 0 )
          return;
      if ( $(e.target).is($root_path) )
          return;

      callback();
    });
  }

  function initMap() {
    var root_path = 'google_map', zoom = 15,
        lat = 37.779628, lng = -122.40663599999999;

    var root = document.getElementById(root_path);
    var $root_path = '#' + root_path;
    var $root = $($root_path);

    var map = new google.maps.Map(root, {
      zoom: zoom,
      center: new google.maps.LatLng(lat, lng),
      draggable: true,
      scrollwheel: false,
      zoomControl: true
    });
    var marker = new google.maps.Marker({
      map: map, position: new google.maps.LatLng(lat, lng)
    });

    $root.on('click', function() {
      map.setOptions({
        scrollwheel: true
      });
    });
    onClickOutside($root_path, function() {
      map.setOptions({
        scrollwheel: false
      })
    });
  }
</script>

<%= render :layout => '/pages/main', :locals => {active: 'contact'} do %>

  <div class="wrapper wrapper-style1">
    <div class="container">
      <div class="row">
        <div class="12u">
          <section id="contact-intro">
            <header class="section-header">
              <h2 class="section-headline">Contact Me</h2>
            </header>
          </section>

          <div id="google_map_container">
            <div id='google_map'></div>
          </div>
          <script src="https://maps.googleapis.com/maps/api/js?callback=initMap" async defer>
          </script>

        </div> <!-- end .12u -->
      </div> <!-- end .row -->
    </div> <!-- end .container -->


    <div class="container">
      <div class="row">
        <div class="7u 12u(mobile)">
          <%= render 'contact_methods', current_user: @current_user %>
        </div>
        <div class="5u 12u(mobile)">
          <%= render 'contact_social_media', current_user: @current_user %>
        </div>
      </div> <!-- end .row -->
    </div> <!-- end .container -->

  </div> <!-- end .wrapper -->

<% end %>

app/views/pages/home.html.erb
<div id="page-wrapper">
	<%= render 'header', active: 'home' %>


	<div class="banner-wrapper">
		<div id="banner">
			<%= render 'banner', current_user: @current_user %>
		</div> <!-- End #banner -->


	</div> <!-- .banner-wrapper -->


	<!-- Main Wrapper -->
	<div id="main-wrapper">
		<div id="main" class="container">
			<%= render 'skills', current_user: @current_user %>
			<%= render 'about', current_user: @current_user %>
		</div> <!-- End #main.container -->

		<div class="clear-footer"></div>
	</div> <!-- End #main-wrapper -->

</div> <!-- end #page-wrapper -->

<!-- Footer Wrapper -->
<%= render 'footer' %>

app/views/pages/no_sidebar.html.erb
<div class="no-sidebar">
	<div id="page-wrapper">

    <%= render 'header', active: 'no_sidebar' %>

		<!-- Main Wrapper -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<div class="row 200%">

						<div class="12u">
							<!-- Content -->
								<div id="content">
									<section class="box post">
										<header>
											<h2>No Sidebar</h2>
										</header>
										<a href="#" class="image left"><img src="images/pic09.jpg" alt=""></a>
                                        <p>Vivamus ut mauris tempus sodales adipiscing in vel quam. Nam erat a posuere laoreet eget nibh sodales adipiscing in vel dolore. Phasellus vitae tristique dui. Duis arcu tortor, fringilla sed venenatis sed, pharetra ac velit. Sed in volutpat nisl. Mauris vel sagittis diam. Lorem ipsum dolor sit amet, consectetur sed adipiscing elit. Pellentesque nec metus feugiat lorem tempus suscipit eros quis accumsan.  Phasellus vitae tristique dui. Duis arcu tortor, fringilla sed venenatis sed, pharetra ac velit. Sed in volutpat nisl dolore ipsum. Maecenas pede nisl, elementum eu, ornare ac, malesuada at, erat. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque eleifend. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. </p>
                                        <p>Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Aliquam libero. Vivamus nisl nibh, iaculis vitae, viverra sit amet, ullamcorper vitae, turpis. Aliquam erat volutpat. Vestibulum dui sem, pulvinar sed, imperdiet nec, iaculis nec, leo. Fusce odio. Etiam arcu dui, faucibus eget, placerat vel, sodales eget, orci. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque eleifend. Phasellus tempor vehicula justo. Aliquam lacinia metus ut elit. Suspendisse iaculis mauris nec lorem. Donec leo. Vivamus fermentum nibh in augue. Praesent a lacus at urna congue rutrum. Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Quisque erat. Vestibulum pellentesque, justo mollis pretium suscipit, justo nulla blandit libero, in blandit augue justo quis nisl. Fusce mattis viverra elit. Fusce quis tortor. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate justo. Donec nonummy magna quis risus. Donec condimentum, urna non molestie semper quis laoreet eros quam eget ante. </p>
                                        <p>Aliquam libero. Vivamus nisl nibh, iaculis vitae, viverra sit amet, ullamcorper vitae, turpis. Aliquam erat volutpat. Vestibulum dui sem, pulvinar sed, imperdiet nec, iaculis nec, leo. Fusce odio. Etiam arcu dui, faucibus eget, placerat vel, sodales eget, orci. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque eleifend. Phasellus tempor vehicula justo. Aliquam lacinia metus ut elit. Suspendisse iaculis mauris nec lorem. Donec leo. Vivamus fermentum nibh in augue. Praesent a lacus at urna congue rutrum. Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque erat. Vestibulum pellentesque, justo mollis pretium suscipit, justo nulla blandit libero, in blandit augue justo quis nisl. Fusce mattis viverra elit. Fusce quis tortor. Proin gravida orci porttitor enim accumsan lacinia.									</p>
									</section>
								</div>

						</div>

					</div>
				</div>

			</div>

		<!-- Footer Wrapper -->
		<%= render 'footer' %>

	</div>

	<!-- Scripts -->
		<script src="assets/javascripts/jquery.min.js"></script>
		<script src="assets/javascripts/jquery.dropotron.min.js"></script>
		<script src="assets/javascripts/skel.min.js"></script>
		<script src="assets/javascripts/skel-viewport.min.js"></script>
		<script src="assets/javascripts/util.js"></script>
		<!--[if lte IE 8]><script src="assets/javascripts/ie/respond.min.js"></script><![endif]-->
		<script src="assets/javascripts/main.js"></script>

</div>

app/views/pages/portfolio.html.erb
<div id="page-wrapper">
	<%= render 'header', active: 'portfolio' %>


	<!-- Main Wrapper -->
	<div id="main-wrapper">
		<div id="main" class="container">

				<!-- Features -->
				<div class="wrapper wrapper-style1">
					<div class="container">
						<div class="row">
							<div class="12u">

								<!-- Featured -->
									<div id="featured">

									<section id="projects-intro">
										<header class="section-header">
											<h2 class="section-headline">
												<span class="group">Projects</span>&nbsp;/&nbsp;
												<span class="group">Portfolio</span>
											</h2>
											<p class="section-caption">
												A mixture of front end CSS and Javascript games, to full stack clones of social networking sites in the middle.
												Finally on the deep back-end of programming, low level libraries in math and meta-programming.
											</p>
										</header>

											<div class="row">
												<% @current_user.projects.each do |project| %>
													<%= render 'project', project: project %>
												<% end %>
											</div> <!-- end .row -->

										</section>

									</div>


							</div>
						</div>
					</div>
				</div>

		</div> <!-- End #main.container -->

		<div class="clear-footer"></div>
	</div> <!-- End #main-wrapper -->

</div> <!-- end #page-wrapper -->

<!-- Footer Wrapper -->
<%= render 'footer' %>

app/views/pages/right_sidebar.html.erb
<div class="right-sidebar">
	<div id="page-wrapper">

    <%= render 'header', active: 'right_sidebar' %>

		<!-- Main Wrapper -->
			<div id="main-wrapper">
				<div id="main" class="container">
					<div class="row 200%">

						<div class="8u 12u(mobile)">

							<!-- Content -->
								<div id="content">
									<section class="box post">
										<header>
											<h2>Right Sidebar</h2>
										</header>
										<a href="#" class="image left"><img src="images/pic08.jpg" alt=""></a>
                                        <p><strong>Vivamus ut mauris tempus</strong> sodales adipiscing in vel quam. Nam erat a posuere laoreet eget nibh sodales adipiscing in vel dolore. Phasellus vitae tristique dui. Duis arcu tortor, fringilla sed venenatis sed, pharetra ac velit. Sed in volutpat nisl. Mauris vel sagittis diam. Lorem ipsum dolor sit amet, consectetur sed adipiscing elit. Proin gravida orci porttitor enim accumsan lacinia. Donec condimentum, urna non molestie semper, ligula enim ornare nibh, quis laoreet eros quam eget ante. Aliquam libero. </p>
                                        <p>Etiam arcu dui, faucibus eget, placerat vel, sodales eget, orci. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque eleifend. Phasellus tempor vehicula justo. Aliquam lacinia metus ut elit. Suspendisse iaculis mauris nec lorem. Donec leo. Vivamus fermentum nibh in augue. Praesent a lacus at urna congue rutrum. Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Quisque erat.  Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo.</p>
                                        <p>Etiam arcu dui, faucibus eget, placerat vel, sodales eget, orci. Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo. Donec nonummy magna quis risus. Quisque eleifend. Phasellus tempor vehicula justo. Aliquam lacinia metus ut elit. Suspendisse iaculis mauris nec lorem. Donec leo. Vivamus fermentum nibh in augue. Praesent a lacus at urna congue rutrum. Nulla enim eros, porttitor eu, tempus id, varius non, nibh. Duis enim nulla, luctus eu, dapibus lacinia, venenatis id, quam. Vestibulum imperdiet, magna nec eleifend rutrum, nunc lectus vestibulum velit, euismod lacinia quam nisl id lorem. Quisque erat.  Donec ornare neque ac sem. Mauris aliquet. Aliquam sem leo, vulputate sed, convallis at, ultricies quis, justo.</p>
									</section>
								</div>

						</div>

						<div class="4u 12u(mobile)">
							<!-- Sidebar -->
								<div id="sidebar">
									<section>
										<header>
											<h2>Curabitur lorem nisl dolor</h2>
										</header>
										<ul class="style2">
											<li class="first">
												<h3>Aliquam erat volutpat class aptent</h3>
												<p><span class="date">6 hours ago</span><span class="comments"><a href="#">32 comments</a></span></p>
											</li>
											<li>
												<h3>Taciti sociosqu ad litora torquent conubia</h3>
												<p><span class="date">9 hours ago</span><span class="comments"><a href="#">28 comments</a></span></p>
											</li>
											<li>
												<h3>Nostra per inceptos himenaeos suspendisse</h3>
												<p><span class="date">9 hours ago</span><span class="comments"><a href="#">28 comments</a></span></p>
											</li>
											<li>
												<h3>Nostra per inceptos himenaeos suspendisse</h3>
												<p><span class="date">9 hours ago</span><span class="comments"><a href="#">28 comments</a></span></p>
											</li>
											<li>
												<h3>Quis elementum tempor sed ullamcorper</h3>
												<p><span class="date">9 hours ago</span><span class="comments"><a href="#">28 comments</a></span></p>
											</li>
										</ul>
										<a href="#" class="button icon icon-folder-open-alt">Browse Archives</a>
									</section>
								</div>

						</div>

					</div>
				</div>

			</div>

		<!-- Footer Wrapper -->
		<%= render 'footer' %>

	</div>

	<!-- Scripts -->
		<script src="assets/javascripts/jquery.min.js"></script>
		<script src="assets/javascripts/jquery.dropotron.min.js"></script>
		<script src="assets/javascripts/skel.min.js"></script>
		<script src="assets/javascripts/skel-viewport.min.js"></script>
		<script src="assets/javascripts/util.js"></script>
		<!--[if lte IE 8]><script src="assets/javascripts/ie/respond.min.js"></script><![endif]-->
		<script src="assets/javascripts/main.js"></script>

</div>

app/views/pages/splash.html.erb
<% dct = {active: 'splash', splash: @splash} %>
<%= render :layout => '/pages/main', :locals => dct do %>
	<!-- Banner -->
	<% url = next_splash_path prev: @splash.rank %>

	<div id="banner">

		<section class="active splash-section">
			<p class="splash-contents"><%= @splash.p.html_safe %></p>
			<h2 class="splash-contents"><%= @splash.h2 %></h2>
		</section>

		<ul class="actions actions-centered splash-action" has_delay="<%= !!@has_delay %>">
			<li class="splash-action-item"><a href="<%= contact_path %>"
					class="button big icon fa-check-circle-o">Contact</a>
			</li>
			<li class="splash-action-item"><a href="<%= url %>"
				  class="button alt big icon fa-info-circle">Learn More</a>
			</li>
		</ul>

	</div>


<% end %>